In [0]:
import pandas as pd
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn import feature_extraction
import numpy as np
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [0]:
df = pd.read_json('preprocessing_News_Category_Dataset_v2.json')
df

              category                                               text
0                CRIME  2 mass shootings texas last week 1 tv left hus...
1        ENTERTAINMENT  smith joins diplo nicky jam 2018 world cup off...
2        ENTERTAINMENT  hugh grant marries first time age 57 actor lon...
3        ENTERTAINMENT  jim carrey blasts castrato adam schiff democra...
4        ENTERTAINMENT  julianna margulies uses donald trump poop bags...
5        ENTERTAINMENT  morgan freeman devastated sexual harassment cl...
6        ENTERTAINMENT  donald trump lovin new mcdonald jingle tonight...
7        ENTERTAINMENT  watch amazon prime new week great mini-series ...
8        ENTERTAINMENT  mike myers reveals like fourth austin powers f...
9        ENTERTAINMENT  watch hulu new week getting recent academy awa...
10       ENTERTAINMENT  justin timberlake visits texas school shooting...
11          WORLD NEWS  south korean president meets north korea kim j...
12              IMPACT  way life risk remote oyster-growing region cal...
13            POLITICS  trump crackdown immigrant parents puts kids al...
14            POLITICS  trump son concerned fbi obtained wiretaps puti...
15            POLITICS  edward snowden one trump loves vladimir putin ...
16            POLITICS  booyah obama photographer hilariously trolls t...
17            POLITICS  ireland votes repeal abortion amendment landsl...
18            POLITICS  ryan zinke looks reel back critics grand pivot...
19            POLITICS  trump scottish golf resort pays women signific...
20          WEIRD NEWS  weird father day gifts dad know wants buy bori...
21       ENTERTAINMENT  twitter putstarwarsinotherfilms universally en...
22          WEIRD NEWS  mystery wolf-like animal reportedly shot monta...
23          WORLD NEWS  north korea still open talks trump cancels sum...
24          WORLD NEWS  2 men detonate bomb inside indian restaurant n...
25          WORLD NEWS  thousands travel home ireland vote abortion ac...
26          WORLD NEWS  irish voters set liberalize abortion laws land...
27        BLACK VOICES  warriors coach steve kerr calls nfl ban protes...
28        BLACK VOICES  historic victory barbados elects first female ...
29        BLACK VOICES  police killed least 378 black americans moment...
...                ...                                                ...
189553    QUEER VOICES  chris gregoire washington state governor discu...
189554    QUEER VOICES  glenn close albert nobbs gender bending damage...
189555          IMPACT  tinker change world tinkering hands-on garage-...
189556          IMPACT  pregnant displaced double danger time step eff...
189557          IMPACT  tom brady helps mentor tom martinez find kidne...
189558     ENVIRONMENT  boxer puppy cows make friends walk newcastle v...
189559     ENVIRONMENT  black smoker vents new species discovered near...
189560     ENVIRONMENT  green activists 50 older look today prominent ...
189561     ENVIRONMENT  winter weather photo contest submit pictures s...
189562     ENVIRONMENT  insects top newly discovered species list spec...
189563        BUSINESS  four bank closures mark week january 27 2012 g...
189564        BUSINESS  everything need know overdraft fees [graphic] ...
189565        BUSINESS  walmart waving goodbye greeters 30 years peopl...
189566        BUSINESS  world economic forum fear global contagion dom...
189567        BUSINESS  positive customer experience return investment...
189568   ENTERTAINMENT  sundance ice-t shades american race cinema rep...
189569   ENTERTAINMENT  girl dragon tattoo india release canceled loca...
189570  ARTS & CULTURE  think look chemical brothers concert film set ...
189571  ARTS & CULTURE  matthew marks discusses new la gallery obvious...
189572  ARTS & CULTURE  allard van hoorn urban songline explores relat...
189573            TECH  good games possible think people play zynga ga...
189574            TECH  google+ open teens safeguards part teens exper...
189575            TECH  web wars web wars threaten rage considerable t...
189576            TECH  first white house chief technology officer ane...
189577            TECH  watch top 9 youtube videos week looking see po...
189578            TECH  rim ceo thorsten heins significant plans black...
189579          SPORTS  maria sharapova stunned victoria azarenka aust...
189580          SPORTS  giants patriots jets colts among improbable su...
189581          SPORTS  aldon smith arrested 49ers linebacker busted d...
189582          SPORTS  dwight howard rips teammates magic loss hornet...

[189583 rows x 2 columns]

In [0]:
x = df['text']
y = df['category']

In [0]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size = 0.1, random_state = 7, stratify = y)

In [0]:
vectorized = feature_extraction.text.CountVectorizer(max_features=5000)

In [0]:
vectorized.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=5000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [0]:
x_train_vectorized = vectorized.transform(x_train)
x_test_vectorized = vectorized.transform(x_test)

In [0]:
vect_tfidf = feature_extraction.text.TfidfVectorizer(max_features = 10250)

In [0]:
vect_tfidf.fit(x_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=10250,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [0]:
x_train_tfidf = vect_tfidf.transform(x_train)
x_test_tfidf = vect_tfidf.transform(x_test)

In [0]:
parameters = [{'C' : [0.01, 1, 10],
               'solver' : ['newton-cg', 'sag'],
               'multi_class' : ['multinomial']
                
              }]

In [0]:
mlr_tfidfcv = model_selection.GridSearchCV(LogisticRegression(), param_grid = parameters, scoring='accuracy', cv=5, return_train_score=True)

In [0]:
mlr_tfidfcv.fit(x_train_tfidf, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'C': [0.01, 1, 10], 'multi_class': ['multinomial'],
                          'solver': ['newton-cg', 'sag']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='accuracy', verbose=0)

In [0]:
mlr_tfidfcv.estimator

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
mlr_tfidfcv.best_score_

0.660932811327832

In [0]:
y_pred_tfidf_train = mlr_tfidfcv.predict(x_train_tfidf)

In [0]:
metrics.accuracy_score(y_train, y_pred_tfidf_train)

0.7329039291072769

In [0]:
y_pred_tfidf_test = mlr_tfidfcv.predict(x_test_tfidf)

In [0]:
metrics.accuracy_score(y_test, y_pred_tfidf_test)

0.6672292842449496

In [0]:
cnf_matrix_tfidf = metrics.confusion_matrix(y_test, y_pred_tfidf_test)
df_cnf_matrix = pd.DataFrame(cnf_matrix_tfidf, index = mlr_tfidfcv.classes_, columns = mlr_tfidfcv.classes_)
df_cnf_matrix

                ARTS & CULTURE  BLACK VOICES  ...  WOMEN  WORLD NEWS
ARTS & CULTURE             157             7  ...      9           4
BLACK VOICES                 5           139  ...      1           3
BUSINESS                     3             2  ...      0          14
COMEDY                       2             1  ...      4           1
CRIME                        2            12  ...      4          10
DIVORCE                      1             1  ...      4           0
EDUCATION                    1             3  ...      0           3
ENTERTAINMENT               13            25  ...      8          10
ENVIRONMENT                  2             1  ...      0          17
FIFTY                        2             0  ...      3           1
FOOD & DRINK                 1             1  ...      1           2
GOOD NEWS                    0             1  ...      2           1
HEALTHY LIVING               3             3  ...      4           9
HOME & LIVING                4             0  ...      0           1
IMPACT                       1             5  ...     10          16
LATINO VOICES                1             0  ...      0           2
MEDIA                        2             5  ...      2           8
MONEY                        1             1  ...      0           0
PARENTS                      6             5  ...      7           0
POLITICS                     4            27  ...     16          76
QUEER VOICES                 7             3  ...      6           9
RELIGION                     3             2  ...      1          10
SCIENCE                      3             0  ...      1           3
SPORTS                       1             2  ...      5           7
STYLE & BEAUTY               4             6  ...      4           2
TECH                         1             2  ...      1           5
TRAVEL                       9             0  ...      1          16
WEDDINGS                     0             0  ...      1           1
WEIRD NEWS                   2             2  ...      0           3
WOMEN                        3             5  ...     78           4
WORLD NEWS                   2             3  ...      4         505

[31 rows x 31 columns]

In [0]:
print(metrics.classification_report(y_test, y_pred_tfidf_test), sep = '\n')

                precision    recall  f1-score   support

ARTS & CULTURE       0.64      0.44      0.52       356
  BLACK VOICES       0.53      0.32      0.40       434
      BUSINESS       0.52      0.45      0.48       542
        COMEDY       0.60      0.42      0.49       460
         CRIME       0.58      0.51      0.54       316
       DIVORCE       0.85      0.65      0.74       342
     EDUCATION       0.53      0.34      0.42       198
 ENTERTAINMENT       0.59      0.74      0.65      1461
   ENVIRONMENT       0.52      0.43      0.47       366
         FIFTY       0.57      0.11      0.19       115
  FOOD & DRINK       0.75      0.80      0.77       803
     GOOD NEWS       0.66      0.19      0.30       130
HEALTHY LIVING       0.63      0.84      0.72      2340
 HOME & LIVING       0.79      0.68      0.73       417
        IMPACT       0.46      0.23      0.31       328
 LATINO VOICES       0.84      0.25      0.38       109
         MEDIA       0.58      0.33      0.42       253
         MONEY       0.63      0.36      0.46       171
       PARENTS       0.66      0.75      0.70      1237
      POLITICS       0.70      0.84      0.76      3131
  QUEER VOICES       0.80      0.64      0.71       599
      RELIGION       0.62      0.36      0.46       217
       SCIENCE       0.78      0.40      0.53       191
        SPORTS       0.69      0.65      0.67       449
STYLE & BEAUTY       0.80      0.82      0.81      1137
          TECH       0.58      0.38      0.46       205
        TRAVEL       0.72      0.77      0.74       951
      WEDDINGS       0.80      0.76      0.78       365
    WEIRD NEWS       0.49      0.26      0.34       237
         WOMEN       0.44      0.24      0.31       320
    WORLD NEWS       0.68      0.65      0.66       779

      accuracy                           0.67     18959
     macro avg       0.65      0.50      0.55     18959
  weighted avg       0.66      0.67      0.65     18959

In [0]:
mlr_vectcv = model_selection.GridSearchCV(LogisticRegression(), param_grid = parameters, scoring='accuracy', cv=5, return_train_score=True)

In [0]:
mlr_vectcv.fit(x_train_vectorized, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'C': [0.01, 1, 10], 'multi_class': ['multinomial'],
                          'solver': ['newton-cg', 'sag']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='accuracy', verbose=0)

In [0]:
mlr_vectcv.best_estimator_

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
mlr_vectcv.best_score_

0.6248065922730682

In [0]:
y_pred_vec_train = mlr_vectcv.predict(x_train_vectorized)

In [0]:
metrics.accuracy_score(y_train, y_pred_vec_train)

0.7590081114028507

In [0]:
y_pred_vec_test = mlr_vectcv.predict(x_test_vectorized)

In [0]:
metrics.accuracy_score(y_test, y_pred_vec_test)

0.6328392847724036

In [0]:
cnf_matrix_vec = metrics.confusion_matrix(y_test, y_pred_vec_test)
df_cnf_matrix = pd.DataFrame(cnf_matrix_vec, index = mlr_vectcv.classes_, columns = mlr_vectcv.classes_)
df_cnf_matrix

                ARTS & CULTURE  BLACK VOICES  ...  WOMEN  WORLD NEWS
ARTS & CULTURE             151             5  ...      4           8
BLACK VOICES                 8           144  ...      1           1
BUSINESS                     6             4  ...      3          17
COMEDY                       4             3  ...      3           1
CRIME                        2            14  ...      3          11
DIVORCE                      1             1  ...      3           0
EDUCATION                    1             5  ...      2           4
ENTERTAINMENT               27            38  ...     17           9
ENVIRONMENT                  3             2  ...      1          18
FIFTY                        1             0  ...      4           0
FOOD & DRINK                 0             4  ...      2           2
GOOD NEWS                    1             2  ...      2           1
HEALTHY LIVING               7             5  ...     20          12
HOME & LIVING                5             1  ...      0           3
IMPACT                       2             7  ...      7          19
LATINO VOICES                1             4  ...      0           3
MEDIA                        5             6  ...      2          14
MONEY                        2             3  ...      0           1
PARENTS                     12             7  ...     17           4
POLITICS                     8            32  ...     16          95
QUEER VOICES                10             3  ...      7          11
RELIGION                     5             2  ...      1          12
SCIENCE                      6             0  ...      0           7
SPORTS                       2             2  ...      2           6
STYLE & BEAUTY              12             7  ...     11           1
TECH                         3             3  ...      2           4
TRAVEL                      10             2  ...      2          18
WEDDINGS                     1             1  ...      3           2
WEIRD NEWS                   2             0  ...      2           1
WOMEN                        3             7  ...     63           7
WORLD NEWS                   6             3  ...      2         488

[31 rows x 31 columns]

In [0]:
print(metrics.classification_report(y_test, y_pred_vec_test), sep = '\n')

                precision    recall  f1-score   support

ARTS & CULTURE       0.49      0.42      0.46       356
  BLACK VOICES       0.45      0.33      0.38       434
      BUSINESS       0.44      0.38      0.41       542
        COMEDY       0.53      0.42      0.47       460
         CRIME       0.51      0.49      0.50       316
       DIVORCE       0.77      0.70      0.74       342
     EDUCATION       0.46      0.33      0.39       198
 ENTERTAINMENT       0.56      0.68      0.62      1461
   ENVIRONMENT       0.45      0.40      0.43       366
         FIFTY       0.25      0.14      0.18       115
  FOOD & DRINK       0.69      0.76      0.73       803
     GOOD NEWS       0.34      0.25      0.29       130
HEALTHY LIVING       0.67      0.76      0.71      2340
 HOME & LIVING       0.71      0.65      0.68       417
        IMPACT       0.38      0.28      0.32       328
 LATINO VOICES       0.48      0.28      0.35       109
         MEDIA       0.46      0.31      0.37       253
         MONEY       0.46      0.36      0.40       171
       PARENTS       0.66      0.69      0.67      1237
      POLITICS       0.71      0.80      0.75      3131
  QUEER VOICES       0.70      0.64      0.67       599
      RELIGION       0.51      0.35      0.42       217
       SCIENCE       0.56      0.43      0.49       191
        SPORTS       0.62      0.62      0.62       449
STYLE & BEAUTY       0.77      0.77      0.77      1137
          TECH       0.49      0.39      0.44       205
        TRAVEL       0.70      0.71      0.71       951
      WEDDINGS       0.76      0.72      0.74       365
    WEIRD NEWS       0.37      0.31      0.34       237
         WOMEN       0.31      0.20      0.24       320
    WORLD NEWS       0.63      0.63      0.63       779

      accuracy                           0.63     18959
     macro avg       0.55      0.49      0.51     18959
  weighted avg       0.62      0.63      0.62     18959